providers = ["flutter"]

[phases.setup]
nixpkgs = ["flutter", "nodejs", "coreutils"]

[phases.install]
cmds = [
  "flutter config --enable-web",
  "flutter pub get"
]

[phases.build]
cmds = [
  "flutter build web"
]

[phases.start]
cmds = [
  "npx --yes serve -s build/web -l ${PORT}"
]
