[phases.setup]
nixpkgs = ["flutter", "nodejs"]

[phases.build]
cmds = [
  "flutter config --enable-web",
  "flutter pub get",
  "flutter build web"
]

[phases.start]
cmds = ["npx serve -s build/web -l ${PORT}"]
