[phases.setup]
nixpkgs = ["flutter", "nodejs"]

[phases.install]
cmds = [
  "flutter config --enable-web",
  "flutter pub get",
  "npm install -g serve"
]

[phases.build]
cmds = [
  "flutter build web"
]

[phases.start]
cmds = [
  "serve -s build/web -l ${PORT}"
]
